### ISSUE TITLE
Question about the n_clusters

### ISSUE THREAD

**Issue by yulijia** [sabrinar/Dhaka#1]
Hi,

I have a question about the clustering method in Dhaka. I read the code and find that the number of k means clusters is 6, https://github.com/sabrinar/Dhaka/blob/master/autoencoder/Dhaka.py#L155

Does it mean that I can only get 6 clusters after running the program (no matter how many true clusters in my input dataset)?

Do I need to change this value (`n_clusters`) during processing my dataset with Dhaka? 

Many thanks,
Lijia

**Comment by sabrinar** [comment]
you can change the value of n_cluster to best suit your data. Also the algorithm has an option to estimate number of clusters from the data, https://github.com/sabrinar/Dhaka/blob/master/autoencoder/Dhaka.py#L276. You can use either of these two options.
